# Generated by Django 4.0.2 on 2022-02-11 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yolo_site', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='Salary',
            new_name='salary',
        ),
        migrations.DeleteModel(
            name='SalesReport',
        ),
    ]
