# Generated by Django 4.0.2 on 2022-02-14 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yolo_site', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='unit',
            field=models.CharField(blank=True, choices=[('mg', 'Mg'), ('mcg', 'Mcg')], max_length=128, null=True),
        ),
    ]
